export const transactionTypes = {
    LOAD_TRANSACTION_DETAILS_REQUEST : "LOADTRANSACTION_DETAILS_REQUEST",
    LOAD_TRANSACTION_DETAILS_SUCCESS : "LOAD_TRANSACTION_DETAILS_SUCCESS",
    LOAD_TRANSACTION_DETAILS_FAILURE : "LOAD_TRANSACTION_DETAILS_FAILURE"
  };